server:
  port: 8765

zuul:
  retryable: true
  routes:
    authenticationservice-api:
      path: '/api/authentication/**'
#      serviceId: 'authenticationService'
    userservice-api:
      path: '/api/user/**'
#      serviceId: 'userService'
    messageservice-api:
      path: 'api/messages/**'
#      serviceId: 'messageService'

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

spring:
  application:
    name: gateway

ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServers: 5

---
spring:
  profiles: docker
eureka:
  client:
    service-url:
      defaultZone: 'http://cloudchat-server:8761/eureka'
