server:
  port: 8888

spring:
  application:
    name: authenticationService
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

oauth.github:
  client-id: 7fc4e156cc81557df516
  client-secret: 8fd0cdc9ca5849d209b745933ffc5705b8fc0b45

jwt.secretKey: SECRETKEYFORJWTTOKENSECRETKEYFORJWTTOKENSECRETKEYFORJWTTOKENSECRETKEYFORJWTTOKEN

---

spring:
  profiles: docker

eureka:
  client:
    service-url:
      defaultZone: 'http://cloudchat-server:8761/eureka'

---
spring:
  profiles: kubernetes
  data:
    mongodb:
      host: mongodb
      password: ${MONGO_PASSWORD}
      port: 27017
      database: ${MONGO_DATABASE}
      username: ${MONGO_USERNAME}
  cloud:
    kubernetes:
      discovery:
        enabled: true
