server:
  port: 50001

spring:
  application:
    name: userService
  data:
    mongodb:
      database: userService
      host: localhost
      port: 27017

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

---
spring:
  profiles: docker
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb/${MONGO_DATABASE}

eureka:
  client:
    service-url:
      defaultZone: 'http://cloudchat-server:8761/eureka'

---
spring:
  profiles: kubernetes
  data:
    mongodb:
#      uri: mongodb://oytech:password!2@mongodb/${MONGO_DATABASE}
      host: mongodb
      password: password!2
      port: 27017
      database: userService
      username: oytech
  cloud:
    kubernetes:
      discovery:
        enabled: true
