server:
  port: 0

spring:
  application:
    name: userService
  data:
    mongodb:
      database: userService
      host: localhost
      port: 27017

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

---
spring:
     profiles: docker
     data:
       mongodb:
         database: userService
         host: host.docker.internal
         port: 27017

eureka:
  client:
    service-url:
      defaultZone: 'http://cloudchat-server:8761/eureka'

